### ISSUE TITLE
Torches not properly mounted to walls

### ISSUE THREAD

**Issue by ExcaliburZero** [slemonide/worms#2]
Currently the torch nodes that are placed by nyan cats are not always properly attached to walls.

However, a method could be created to when a torch is placed to check all of the nodes immediately surrounding the torch (6 nodes) and see if any node is at those points. Then if there is a node next to the torch, the torch becomes mounted to that node.

This could likely be done somehow with the [minetest.dir_to_wallmounted](http://dev.minetest.net/minetest.dir_to_wallmounted) function setting the param2 of the torch when it finds a node next to the torch.

**Comment by slemonide** [comment]
I fixed that by making nyancats place turches only on the ceilings. Though they still could carve tunnels through the ceilings and that would make torches float in the air.
